const { test } = require('node:test');
const assert = require('node:assert/strict');
const User = require('../src/models/User');
const { hashPassword, verifyPassword } = require('../src/utils/password');
const app = require('../src/app');

test('schema validation and password hashing', async () => {
  const empty = new User().validateSync();
  for (const key of ['name', 'email', 'passwordHash']) assert.ok(empty.errors[key]);
  const hash = await hashPassword('a-long-test-password');
  assert.ok(await verifyPassword('a-long-test-password', hash));
  assert.equal(await verifyPassword('incorrect', hash), false);
  assert.notEqual(hash, await hashPassword('a-long-test-password'));
  const user = new User({ name: ' Test ', email: ' TEST@EXAMPLE.COM ', passwordHash: hash });
  assert.equal(user.validateSync(), undefined);
  assert.equal(user.email, 'test@example.com');
  assert.equal(user.role, 'retailUser');
  assert.equal(user.toJSON().passwordHash, undefined);
  assert.equal(user.toJSON().tokenVersion, undefined);
  user.role = 'owner';
  assert.ok(user.validateSync().errors.role);
});

test('public user CRUD and credential-only login (in-memory repository)', async t => {
  const records = new Map();
  t.mock.method(User, 'findById', async id => records.get(String(id)) || null);
  t.mock.method(User, 'findOne', filter => ({ select: async () => [...records.values()].find(u => u.email === filter.email) || null }));
  t.mock.method(User, 'find', () => ({ sort: () => ({ skip: offset => ({ limit: async limit => [...records.values()].slice(offset, offset + limit) }) }) }));
  t.mock.method(User, 'countDocuments', async () => records.size);
  t.mock.method(User, 'create', async data => {
    const user = new User(data);
    await user.validate();
    if ([...records.values()].some(u => u.email === user.email)) throw Object.assign(new Error('duplicate'), { code: 11000 });
    user.save = async () => { await user.validate(); return user; };
    records.set(String(user._id), user);
    return user;
  });
  t.mock.method(User, 'deleteOne', async filter => records.delete(String(filter._id)));
  const server = app.listen(0, '127.0.0.1');
  t.after(() => { server.close(); server.closeAllConnections(); });
  await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
  const base = `http://127.0.0.1:${server.address().port}/api`;
  async function call(path, method = 'GET', body) {
    const response = await fetch(base + path, { method, headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
    return { status: response.status, body: response.status === 204 ? null : await response.json() };
  }
  assert.equal((await call('/admin/health')).status, 200);
  assert.equal((await call('/health')).status, 503);
  assert.equal((await call('/users')).status, 200);
  const data = { name: 'Customer', email: 'customer@example.com', password: 'long-enough-password' };
  const created = await call('/auth/register', 'POST', data);
  assert.equal(created.status, 201);
  assert.deepEqual(Object.keys(created.body), ['user']);
  assert.equal(created.body.user.passwordHash, undefined);
  assert.equal((await call('/auth/register', 'POST', data)).status, 409);
  assert.equal((await call('/auth/register', 'POST', { ...data, password: 'short' })).status, 400);
  const id = created.body.user._id;
  const login = await call('/auth/login', 'POST', { email: data.email, password: data.password });
  assert.equal(login.status, 200);
  assert.deepEqual(Object.keys(login.body), ['flag', 'data']);
  assert.equal(login.body.flag, true);
  assert.equal(login.body.data._id, id);
  assert.equal(login.body.data.passwordHash, undefined);
  assert.equal((await call('/auth/login', 'POST', { email: data.email, password: 'wrong' })).status, 401);
  assert.equal((await call('/auth/login', 'POST', { email: { $ne: '' }, password: data.password })).status, 400);
  assert.equal((await call('/admin/login', 'POST', { email: data.email, password: data.password })).status, 401);
  const admin = await call('/users', 'POST', { ...data, email: 'admin@example.com', role: 'admin' });
  assert.equal(admin.status, 201);
  const adminLogin = await call('/admin/login', 'POST', { email: 'admin@example.com', password: data.password });
  assert.equal(adminLogin.status, 200);
  assert.deepEqual(Object.keys(adminLogin.body), ['flag', 'data']);
  assert.equal(adminLogin.body.flag, true);
  assert.equal(adminLogin.body.data.role, 'admin');
  assert.equal(adminLogin.body.data.passwordHash, undefined);
  await call('/users/' + admin.body.user._id, 'PATCH', { isActive: false });
  const inactiveAdmin = await call('/admin/login', 'POST', { email: 'admin@example.com', password: data.password });
  assert.equal(inactiveAdmin.status, 401);
  assert.deepEqual(inactiveAdmin.body, { flag: false, data: null, error: 'Invalid email or password' });
  assert.equal((await call('/auth/login', 'POST', { email: 'admin@example.com', password: data.password })).status, 401);
  assert.equal((await call('/users')).body.total, 2);
  assert.equal((await call('/users?page=0')).status, 400);
  assert.equal((await call('/users/' + id)).status, 200);
  assert.equal((await call('/users/bad')).status, 400);
  assert.equal((await call('/users/000000000000000000000000')).status, 404);
  const updated = await call('/users/' + id, 'PATCH', { password: 'new-long-password', role: 'wholesaleUser', name: 'Updated' });
  assert.equal(updated.status, 200);
  assert.equal(updated.body.user.passwordHash, undefined);
  assert.equal(updated.body.user.role, 'wholesaleUser');
  assert.equal((await call('/auth/login', 'POST', { email: data.email, password: 'new-long-password' })).status, 200);
  assert.equal((await call('/users/' + id, 'PATCH', { isActive: false })).status, 200);
  const inactiveUser = await call('/auth/login', 'POST', { email: data.email, password: 'new-long-password' });
  assert.equal(inactiveUser.status, 401);
  assert.deepEqual(inactiveUser.body, { flag: false, data: null, error: 'Invalid email or password' });
  assert.equal((await call('/users/' + id, 'PATCH', { passwordHash: 'injected' })).status, 400);
  assert.equal((await call('/users/' + id, 'PATCH', {})).status, 400);
  assert.equal((await call('/users/' + admin.body.user._id, 'DELETE')).status, 204);
  assert.equal((await call('/users/' + id, 'DELETE')).status, 204);
  assert.equal((await call('/users/' + id)).status, 404);
  assert.equal((await call('/auth/logout', 'POST')).status, 404);
  const malformed = await fetch(base + '/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{' });
  assert.equal(malformed.status, 400);
  assert.deepEqual(await malformed.json(), { flag: false, data: null, error: 'Invalid request' });
  for (let i = 0; i < 21; i++) await call('/auth/login', 'POST', {});
  const throttled = await call('/auth/login', 'POST', {});
  assert.equal(throttled.status, 429);
  assert.equal(throttled.body.flag, false);
  assert.equal(throttled.body.data, null);
});
